#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc &

if [[ $(xrandr -q | grep "HDMI-A-0 connected") ]];then
  xrandr --output HDMI-A-0 --primary --output eDP --right-of HDMI-A-0
  bspc monitor HDMI-A-0 -d 1 2 3
  bspc monitor eDP -d 4 5
else
  bspc monitor eDP -d 1 2 3 4 5
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/bspwm/autostart
